plugins:     ./docs/_plugins
data_source: ./_posts
layouts:     ./docs/_layouts

type: "pages"

exclude: ["coral-core", "runtime-api", "project", "cluster", "examples", "target", "init.py", "Procfile"]

permalink: none

url: "http://coral-streaming.github.io"
baseurl: "/coral"


